---
vxlan:
  fabric:
    name: nac-fabric1
    type: VXLAN_EVPN
  global:
    bgp_asn: "65999"
    route_reflectors: 2
    anycast_gateway_mac: 12:34:56:78:90:00
    dns_servers:
      - ip_address: 10.0.226.251
        vrf: management
    ntp_servers:
      - ip_address: 10.81.254.202
        vrf: management
