vxlan:
  topology:
    switches:
    - name: Site1-S1
      role: spine
      serial_number: 9515VCXDG9B
      management:
        default_gateway_v4: 10.3.29.1
        default_gateway_v6: 2055:55:55:55::55/64
        management_ipv4_address: 10.3.29.11
        management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1
      # poap:
      #  bootstrap: true
    - name: Site1-S2
      role: spine
      serial_number: 9W56PH2JGHT
      management:
        default_gateway_v4: 10.3.29.1
        default_gateway_v6: 2055:55:55:55::55/64
        management_ipv4_address: 10.3.29.12
        management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1      
      # poap:
      #   bootstrap: true 
    - name: Site1-L1
      role: leaf
      serial_number: 9OI9I0ZQO7L
      management:
        default_gateway_v4: 10.3.29.1
        default_gateway_v6: 2055:55:55:55::55/64
        management_ipv4_address: 10.3.29.13
        management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1
      # poap:
      #  bootstrap: true
    - name: Site1-L2
      role: leaf
      serial_number: 9VFK4RA9VTB
      management:
        default_gateway_v4: 10.3.29.1
        default_gateway_v6: 2055:55:55:55::55/64
        management_ipv4_address: 10.3.29.14
        management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1
      # poap:
      #  bootstrap: true
    - name: Site1-BL1
      serial_number: 9IX1L7ZPQ2Q
      role: border
      management:
          default_gateway_v4: 10.3.29.1
          default_gateway_v6: 2055:55:55:55::55/64
          management_ipv4_address: 10.3.29.15
          management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1
      # poap:
      #  bootstrap: true
    - name: Site1-BGW1
      serial_number: 9187EL82V60
      role: border_gateway
      management:
          default_gateway_v4: 10.3.29.1
          default_gateway_v6: 2055:55:55:55::55/64
          management_ipv4_address: 10.3.29.16
          management_ipv6_address: 2055:55:55:55::55/64
      routing_loopback_id: 0
      vtep_loopback_id: 1
      # poap:
      #  bootstrap: true